MODLOGSAML-151: JDK 17: java.base does not "opens java.util.concurrent.atomic"
Use JDK 17 and run "mvn clean install".

Build fails with this error:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final jdk.internal.misc.Unsafe java.util.concurrent.atomic.AtomicInteger.U accessible: module java.base does not "opens java.util.concurrent.atomic" to unnamed module @62bd2070
        at org.folio.util.DumpUtilTest.dumpContent(DumpUtilTest.java:26)
```

This is caused by the strong encapsulation of the Java Platform Module System.

Fixing it is easy because it is in the unit test only, not in the production code.